# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9729a450aea3295a57d127878e96b4be2f20b1843e144d05f50d064e2bf426dbe04c0452e809a4b588b14fa5be693b5bfbb98abbc549b3643f95602db29c6229

test:
  secret_key_base: 7fc34bee6de4228592049f579cae8ee6c856b8f72c43f658d9e73b747533d577e314d94d493b827ac01181f39424e319dc16ceec7306cc93ce802df125388b8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
